"use strict";

module.exports = {

    SANDP_STOCK_SYMBOLS: [
        {name: "3M Company", symbol: "MMM"},
        {name: "Abbott Laboratories", symbol: "ABT"},
        {name: "AbbVie", symbol: "ABBV"},
        {name: "Accenture plc", symbol: "ACN"},
        {name: "Activision Blizzard", symbol: "ATVI"},
        {name: "Acuity Brands Inc", symbol: "AYI"},
        {name: "Adobe Systems Inc", symbol: "ADBE"},
        {name: "Advance Auto Parts", symbol: "AAP"},
        {name: "AES Corp", symbol: "AES"},
        {name: "Aetna Inc", symbol: "AET"},
        {name: "Affiliated Managers Group Inc", symbol: "AMG"},
        {name: "AFLAC Inc", symbol: "AFL"},
        {name: "Agilent Technologies Inc", symbol: "A"},
        {name: "Air Products & Chemicals Inc", symbol: "APD"},
        {name: "Akamai Technologies Inc", symbol: "AKAM"},
        {name: "Alaska Air Group Inc", symbol: "ALK"},
        {name: "Albemarle Corp", symbol: "ALB"},
        {name: "Alcoa Inc", symbol: "AA"},
        {name: "Alexion Pharmaceuticals", symbol: "ALXN"},
        {name: "Allegion", symbol: "ALLE"},
        {name: "Allergan plc", symbol: "AGN"},
        {name: "Alliance Data Systems", symbol: "ADS"},
        {name: "Alliant Energy Corp", symbol: "LNT"},
        {name: "Allstate Corp", symbol: "ALL"},
        {name: "Alphabet Inc Class A", symbol: "GOOGL"},
        {name: "Alphabet Inc Class C", symbol: "GOOG"},
        {name: "Altria Group Inc", symbol: "MO"},
        {name: "Amazon.com Inc", symbol: "AMZN"},
        {name: "Ameren Corp", symbol: "AEE"},
        {name: "American Airlines Group", symbol: "AAL"},
        {name: "American Electric Power", symbol: "AEP"},
        {name: "American Express Co", symbol: "AXP"},
        {name: "American International Group, Inc.", symbol: "AIG"},
        {name: "American Tower Corp A", symbol: "AMT"},
        {name: "American Water Works Company Inc", symbol: "AWK"},
        {name: "Ameriprise Financial", symbol: "AMP"},
        {name: "AmerisourceBergen Corp", symbol: "ABC"},
        {name: "Ametek", symbol: "AME"},
        {name: "Amgen Inc", symbol: "AMGN"},
        {name: "Amphenol Corp A", symbol: "APH"},
        {name: "Anadarko Petroleum Corp", symbol: "APC"},
        {name: "Analog Devices, Inc.", symbol: "ADI"},
        {name: "Anthem Inc.", symbol: "ANTM"},
        {name: "Aon plc", symbol: "AON"},
        {name: "Apache Corporation", symbol: "APA"},
        {name: "Apartment Investment & Mgmt", symbol: "AIV"},
        {name: "Apple Inc.", symbol: "AAPL"},
        {name: "Applied Materials Inc", symbol: "AMAT"},
        {name: "Archer-Daniels-Midland Co", symbol: "ADM"},
        {name: "Arthur J. Gallagher & Co.", symbol: "AJG"},
        {name: "Assurant Inc", symbol: "AIZ"},
        {name: "AT&T Inc", symbol: "T"},
        {name: "Autodesk Inc", symbol: "ADSK"},
        {name: "Automatic Data Processing", symbol: "ADP"},
        {name: "AutoNation Inc", symbol: "AN"},
        {name: "AutoZone Inc", symbol: "AZO"},
        {name: "Avago Technologies", symbol: "AVGO"},
        {name: "AvalonBay Communities, Inc.", symbol: "AVB"},
        {name: "Avery Dennison Corp", symbol: "AVY"},
        {name: "Baker Hughes Inc", symbol: "BHI"},
        {name: "Ball Corp", symbol: "BLL"},
        {name: "Bank of America Corp", symbol: "BAC"},
        {name: "Bard (C.R.) Inc.", symbol: "BCR"},
        {name: "Baxter International Inc.", symbol: "BAX"},
        {name: "BB&T Corporation", symbol: "BBT"},
        {name: "Becton Dickinson", symbol: "BDX"},
        {name: "Bed Bath & Beyond", symbol: "BBBY"},
        {name: "Berkshire Hathaway", symbol: "BRK.B"},
        {name: "Best Buy Co. Inc.", symbol: "BBY"},
        {name: "BIOGEN IDEC Inc.", symbol: "BIIB"},
        {name: "BlackRock", symbol: "BLK"},
        {name: "Block H&R", symbol: "HRB"},
        {name: "Boeing Company", symbol: "BA"},
        {name: "BorgWarner", symbol: "BWA"},
        {name: "Boston Properties", symbol: "BXP"},
        {name: "Boston Scientific", symbol: "BSX"},
        {name: "Bristol-Myers Squibb", symbol: "BMY"},
        {name: "Brown-Forman Corporation", symbol: "BF.B"},
        {name: "C. H. Robinson Worldwide", symbol: "CHRW"},
        {name: "CA, Inc.", symbol: "CA"},
        {name: "Cabot Oil & Gas", symbol: "COG"},
        {name: "Campbell Soup", symbol: "CPB"},
        {name: "Capital One Financial", symbol: "COF"},
        {name: "Cardinal Health Inc.", symbol: "CAH"},
        {name: "Carmax Inc", symbol: "KMX"},
        {name: "Carnival Corp.", symbol: "CCL"},
        {name: "Caterpillar Inc.", symbol: "CAT"},
        {name: "CBRE Group", symbol: "CBG"},
        {name: "CBS Corp.", symbol: "CBS"},
        {name: "Celgene Corp.", symbol: "CELG"},
        {name: "Centene Corporation", symbol: "CNC"},
        {name: "CenterPoint Energy", symbol: "CNP"},
        {name: "CenturyLink Inc", symbol: "CTL"},
        {name: "Cerner", symbol: "CERN"},
        {name: "CF Industries Holdings Inc", symbol: "CF"},
        {name: "Charles Schwab Corporation", symbol: "SCHW"},
        {name: "Chesapeake Energy", symbol: "CHK"},
        {name: "Chevron Corp.", symbol: "CVX"},
        {name: "Chipotle Mexican Grill", symbol: "CMG"},
        {name: "Chubb Limited", symbol: "CB"},
        {name: "Church & Dwight", symbol: "CHD"},
        {name: "CIGNA Corp.", symbol: "CI"},
        {name: "Cimarex Energy", symbol: "XEC"},
        {name: "Cincinnati Financial", symbol: "CINF"},
        {name: "Cintas Corporation", symbol: "CTAS"},
        {name: "Cisco Systems", symbol: "CSCO"},
        {name: "Citigroup Inc.", symbol: "C"},
        {name: "Citizens Financial Group", symbol: "CFG"},
        {name: "Citrix Systems", symbol: "CTXS"},
        {name: "CME Group Inc.", symbol: "CME"},
        {name: "CMS Energy", symbol: "CMS"},
        {name: "Coach Inc.", symbol: "COH"},
        {name: "Cognizant Technology Solutions", symbol: "CTSH"},
        {name: "Colgate-Palmolive", symbol: "CL"},
        {name: "Comcast A Corp", symbol: "CMCSA"},
        {name: "Comerica Inc.", symbol: "CMA"},
        {name: "ConAgra Foods Inc.", symbol: "CAG"},
        {name: "Concho Resources", symbol: "CXO"},
        {name: "ConocoPhillips", symbol: "COP"},
        {name: "Consolidated Edison", symbol: "ED"},
        {name: "Constellation Brands", symbol: "STZ"},
        {name: "Corning Inc.", symbol: "GLW"},
        {name: "Costco Co.", symbol: "COST"},
        {name: "Crown Castle International Corp.", symbol: "CCI"},
        {name: "CSRA Inc.", symbol: "CSRA"},
        {name: "CSX Corp.", symbol: "CSX"},
        {name: "Cummins Inc.", symbol: "CMI"},
        {name: "CVS Health", symbol: "CVS"},
        {name: "D. R. Horton", symbol: "DHI"},
        {name: "Danaher Corp.", symbol: "DHR"},
        {name: "Darden Restaurants", symbol: "DRI"},
        {name: "DaVita Inc.", symbol: "DVA"},
        {name: "Deere & Co.", symbol: "DE"},
        {name: "Delphi Automotive", symbol: "DLPH"},
        {name: "Delta Air Lines", symbol: "DAL"},
        {name: "Dentsply Sirona", symbol: "XRAY"},
        {name: "Devon Energy Corp.", symbol: "DVN"},
        {name: "Diamond Offshore Drilling", symbol: "DO"},
        {name: "Digital Realty Trust", symbol: "DLR"},
        {name: "Discover Financial Services", symbol: "DFS"},
        {name: "Discovery Communications-A", symbol: "DISCA"},
        {name: "Discovery Communications-C", symbol: "DISCK"},
        {name: "Dollar General", symbol: "DG"},
        {name: "Dollar Tree", symbol: "DLTR"},
        {name: "Dominion Resources", symbol: "D"},
        {name: "Dover Corp.", symbol: "DOV"},
        {name: "Dow Chemical", symbol: "DOW"},
        {name: "Dr Pepper Snapple Group", symbol: "DPS"},
        {name: "DTE Energy Co.", symbol: "DTE"},
        {name: "Du Pont (E.I.)", symbol: "DD"},
        {name: "Duke Energy", symbol: "DUK"},
        {name: "Dun & Bradstreet", symbol: "DNB"},
        {name: "E*Trade", symbol: "ETFC"},
        {name: "Eastman Chemical", symbol: "EMN"},
        {name: "Eaton Corporation", symbol: "ETN"},
        {name: "eBay Inc.", symbol: "EBAY"},
        {name: "Ecolab Inc.", symbol: "ECL"},
        {name: "Edison Int'l", symbol: "EIX"},
        {name: "Edwards Lifesciences", symbol: "EW"},
        {name: "Electronic Arts", symbol: "EA"},
        {name: "EMC Corp.", symbol: "EMC"},
        {name: "Emerson Electric Company", symbol: "EMR"},
        {name: "Endo International", symbol: "ENDP"},
        {name: "Entergy Corp.", symbol: "ETR"},
        {name: "EOG Resources", symbol: "EOG"},
        {name: "EQT Corporation", symbol: "EQT"},
        {name: "Equifax Inc.", symbol: "EFX"},
        {name: "Equinix", symbol: "EQIX"},
        {name: "Equity Residential", symbol: "EQR"},
        {name: "Essex Property Trust Inc", symbol: "ESS"},
        {name: "Estee Lauder Cos.", symbol: "EL"},
        {name: "Eversource Energy", symbol: "ES"},
        {name: "Exelon Corp.", symbol: "EXC"},
        {name: "Expedia Inc.", symbol: "EXPE"},
        {name: "Expeditors Int'l", symbol: "EXPD"},
        {name: "Express Scripts", symbol: "ESRX"},
        {name: "Extra Space Storage", symbol: "EXR"},
        {name: "Exxon Mobil Corp.", symbol: "XOM"},
        {name: "F5 Networks", symbol: "FFIV"},
        {name: "Facebook", symbol: "FB"},
        {name: "Fastenal Co", symbol: "FAST"},
        {name: "Federal Realty Investment Trust", symbol: "FRT"},
        {name: "FedEx Corporation", symbol: "FDX"},
        {name: "Fidelity National Information Services", symbol: "FIS"},
        {name: "Fifth Third Bancorp", symbol: "FITB"},
        {name: "First Solar Inc", symbol: "FSLR"},
        {name: "FirstEnergy Corp", symbol: "FE"},
        {name: "Fiserv Inc", symbol: "FISV"},
        {name: "FLIR Systems", symbol: "FLIR"},
        {name: "Flowserve Corporation", symbol: "FLS"},
        {name: "Fluor Corp.", symbol: "FLR"},
        {name: "FMC Corporation", symbol: "FMC"},
        {name: "FMC Technologies Inc.", symbol: "FTI"},
        {name: "Foot Locker Inc", symbol: "FL"},
        {name: "Ford Motor", symbol: "F"},
        {name: "Fortive Corp", symbol: "FTV"},
        {name: "Fortune Brands Home & Security", symbol: "FBHS"},
        {name: "Franklin Resources", symbol: "BEN"},
        {name: "Freeport-McMoran Cp & Gld", symbol: "FCX"},
        {name: "Frontier Communications", symbol: "FTR"},
        {name: "Gap (The)", symbol: "GPS"},
        {name: "Garmin Ltd.", symbol: "GRMN"},
        {name: "General Dynamics", symbol: "GD"},
        {name: "General Electric", symbol: "GE"},
        {name: "General Growth Properties Inc.", symbol: "GGP"},
        {name: "General Mills", symbol: "GIS"},
        {name: "General Motors", symbol: "GM"},
        {name: "Genuine Parts", symbol: "GPC"},
        {name: "Gilead Sciences", symbol: "GILD"},
        {name: "Global Payments Inc", symbol: "GPN"},
        {name: "Goldman Sachs Group", symbol: "GS"},
        {name: "Goodyear Tire & Rubber", symbol: "GT"},
        {name: "Grainger (W.W.) Inc.", symbol: "GWW"},
        {name: "Halliburton Co.", symbol: "HAL"},
        {name: "Hanesbrands Inc", symbol: "HBI"},
        {name: "Harley-Davidson", symbol: "HOG"},
        {name: "Harman Int'l Industries", symbol: "HAR"},
        {name: "Harris Corporation", symbol: "HRS"},
        {name: "Hartford Financial Svc.Gp.", symbol: "HIG"},
        {name: "Hasbro Inc.", symbol: "HAS"},
        {name: "HCA Holdings", symbol: "HCA"},
        {name: "HCP Inc.", symbol: "HCP"},
        {name: "Helmerich & Payne", symbol: "HP"},
        {name: "Henry Schein", symbol: "HSIC"},
        {name: "Hess Corporation", symbol: "HES"},
        {name: "Hewlett Packard Enterprise", symbol: "HPE"},
        {name: "Hologic", symbol: "HOLX"},
        {name: "Home Depot", symbol: "HD"},
        {name: "Honeywell Int'l Inc.", symbol: "HON"},
        {name: "Hormel Foods Corp.", symbol: "HRL"},
        {name: "Host Hotels & Resorts", symbol: "HST"},
        {name: "HP Inc.", symbol: "HPQ"},
        {name: "Humana Inc.", symbol: "HUM"},
        {name: "Huntington Bancshares", symbol: "HBAN"},
        {name: "Illinois Tool Works", symbol: "ITW"},
        {name: "Illumina Inc", symbol: "ILMN"},
        {name: "Ingersoll-Rand PLC", symbol: "IR"},
        {name: "Intel Corp.", symbol: "INTC"},
        {name: "Intercontinental Exchange", symbol: "ICE"},
        {name: "International Bus. Machines", symbol: "IBM"},
        {name: "International Paper", symbol: "IP"},
        {name: "Interpublic Group", symbol: "IPG"},
        {name: "Intl Flavors & Fragrances", symbol: "IFF"},
        {name: "Intuit Inc.", symbol: "INTU"},
        {name: "Intuitive Surgical Inc.", symbol: "ISRG"},
        {name: "Invesco Ltd.", symbol: "IVZ"},
        {name: "Iron Mountain Incorporated", symbol: "IRM"},
        {name: "J. B. Hunt Transport Services", symbol: "JBHT"},
        {name: "Jacobs Engineering Group", symbol: "JEC"},
        {name: "Johnson & Johnson", symbol: "JNJ"},
        {name: "Johnson Controls", symbol: "JCI"},
        {name: "JPMorgan Chase & Co.", symbol: "JPM"},
        {name: "Juniper Networks", symbol: "JNPR"},
        {name: "Kansas City Southern", symbol: "KSU"},
        {name: "Kellogg Co.", symbol: "K"},
        {name: "KeyCorp", symbol: "KEY"},
        {name: "Kimberly-Clark", symbol: "KMB"},
        {name: "Kimco Realty", symbol: "KIM"},
        {name: "Kinder Morgan", symbol: "KMI"},
        {name: "KLA-Tencor Corp.", symbol: "KLAC"},
        {name: "Kohl's Corp.", symbol: "KSS"},
        {name: "Kraft Heinz Co", symbol: "KHC"},
        {name: "Kroger Co.", symbol: "KR"},
        {name: "L Brands Inc.", symbol: "LB"},
        {name: "L-3 Communications Holdings", symbol: "LLL"},
        {name: "Laboratory Corp. of America Holding", symbol: "LH"},
        {name: "Lam Research", symbol: "LRCX"},
        {name: "Legg Mason", symbol: "LM"},
        {name: "Leggett & Platt", symbol: "LEG"},
        {name: "Lennar Corp.", symbol: "LEN"},
        {name: "Leucadia National Corp.", symbol: "LUK"},
        {name: "Level 3 Communications", symbol: "LVLT"},
        {name: "Lilly (Eli) & Co.", symbol: "LLY"},
        {name: "Lincoln National", symbol: "LNC"},
        {name: "Linear Technology Corp.", symbol: "LLTC"},
        {name: "LKQ Corporation", symbol: "LKQ"},
        {name: "Lockheed Martin Corp.", symbol: "LMT"},
        {name: "Loews Corp.", symbol: "L"},
        {name: "Lowe's Cos.", symbol: "LOW"},
        {name: "LyondellBasell", symbol: "LYB"},
        {name: "M&T Bank Corp.", symbol: "MTB"},
        {name: "Macerich", symbol: "MAC"},
        {name: "Macy's Inc.", symbol: "M"},
        {name: "Mallinckrodt Plc", symbol: "MNK"},
        {name: "Marathon Oil Corp.", symbol: "MRO"},
        {name: "Marathon Petroleum", symbol: "MPC"},
        {name: "Marriott Int'l.", symbol: "MAR"},
        {name: "Marsh & McLennan", symbol: "MMC"},
        {name: "Martin Marietta Materials", symbol: "MLM"},
        {name: "Masco Corp.", symbol: "MAS"},
        {name: "Mastercard Inc.", symbol: "MA"},
        {name: "Mattel Inc.", symbol: "MAT"},
        {name: "McCormick & Co.", symbol: "MKC"},
        {name: "McDonald's Corp.", symbol: "MCD"},
        {name: "McKesson Corp.", symbol: "MCK"},
        {name: "Mead Johnson", symbol: "MJN"},
        {name: "Medtronic plc", symbol: "MDT"},
        {name: "Merck & Co.", symbol: "MRK"},
        {name: "MetLife Inc.", symbol: "MET"},
        {name: "Michael Kors Holdings", symbol: "KORS"},
        {name: "Microchip Technology", symbol: "MCHP"},
        {name: "Micron Technology", symbol: "MU"},
        {name: "Microsoft Corp.", symbol: "MSFT"},
        {name: "Mohawk Industries", symbol: "MHK"},
        {name: "Molson Coors Brewing Company", symbol: "TAP"},
        {name: "Mondelez International", symbol: "MDLZ"},
        {name: "Monsanto Co.", symbol: "MON"},
        {name: "Monster Beverage", symbol: "MNST"},
        {name: "Moody's Corp", symbol: "MCO"},
        {name: "Morgan Stanley", symbol: "MS"},
        {name: "Motorola Solutions Inc.", symbol: "MSI"},
        {name: "Murphy Oil", symbol: "MUR"},
        {name: "Mylan N.V.", symbol: "MYL"},
        {name: "NASDAQ OMX Group", symbol: "NDAQ"},
        {name: "National Oilwell Varco Inc.", symbol: "NOV"},
        {name: "Navient", symbol: "NAVI"},
        {name: "NetApp", symbol: "NTAP"},
        {name: "Netflix Inc.", symbol: "NFLX"},
        {name: "Newell Rubbermaid Co.", symbol: "NWL"},
        {name: "Newfield Exploration Co", symbol: "NFX"},
        {name: "Newmont Mining Corp. (Hldg. Co.)", symbol: "NEM"},
        {name: "News Corp. Class A", symbol: "NWSA"},
        {name: "News Corp. Class B", symbol: "NWS"},
        {name: "NextEra Energy", symbol: "NEE"},
        {name: "Nielsen Holdings", symbol: "NLSN"},
        {name: "Nike", symbol: "NKE"},
        {name: "NiSource Inc.", symbol: "NI"},
        {name: "Noble Energy Inc", symbol: "NBL"},
        {name: "Nordstrom", symbol: "JWN"},
        {name: "Norfolk Southern Corp.", symbol: "NSC"},
        {name: "Northern Trust Corp.", symbol: "NTRS"},
        {name: "Northrop Grumman Corp.", symbol: "NOC"},
        {name: "NRG Energy", symbol: "NRG"},
        {name: "Nucor Corp.", symbol: "NUE"},
        {name: "Nvidia Corporation", symbol: "NVDA"},
        {name: "O'Reilly Automotive", symbol: "ORLY"},
        {name: "Occidental Petroleum", symbol: "OXY"},
        {name: "Omnicom Group", symbol: "OMC"},
        {name: "ONEOK", symbol: "OKE"},
        {name: "Oracle Corp.", symbol: "ORCL"},
        {name: "Owens-Illinois Inc", symbol: "OI"},
        {name: "PACCAR Inc.", symbol: "PCAR"},
        {name: "Parker-Hannifin", symbol: "PH"},
        {name: "Patterson Companies", symbol: "PDCO"},
        {name: "Paychex Inc.", symbol: "PAYX"},
        {name: "PayPal", symbol: "PYPL"},
        {name: "Pentair Ltd.", symbol: "PNR"},
        {name: "People's United Financial", symbol: "PBCT"},
        {name: "PepsiCo Inc.", symbol: "PEP"},
        {name: "PerkinElmer", symbol: "PKI"},
        {name: "Perrigo", symbol: "PRGO"},
        {name: "Pfizer Inc.", symbol: "PFE"},
        {name: "PG&E Corp.", symbol: "PCG"},
        {name: "Philip Morris International", symbol: "PM"},
        {name: "Phillips 66", symbol: "PSX"},
        {name: "Pinnacle West Capital", symbol: "PNW"},
        {name: "Pioneer Natural Resources", symbol: "PXD"},
        {name: "Pitney-Bowes", symbol: "PBI"},
        {name: "PNC Financial Services", symbol: "PNC"},
        {name: "Polo Ralph Lauren Corp.", symbol: "RL"},
        {name: "PPG Industries", symbol: "PPG"},
        {name: "PPL Corp.", symbol: "PPL"},
        {name: "Praxair Inc.", symbol: "PX"},
        {name: "Priceline.com Inc", symbol: "PCLN"},
        {name: "Principal Financial Group", symbol: "PFG"},
        {name: "Procter & Gamble", symbol: "PG"},
        {name: "Progressive Corp.", symbol: "PGR"},
        {name: "Prologis", symbol: "PLD"},
        {name: "Prudential Financial", symbol: "PRU"},
        {name: "Public Serv. Enterprise Inc.", symbol: "PEG"},
        {name: "Public Storage", symbol: "PSA"},
        {name: "Pulte Homes Inc.", symbol: "PHM"},
        {name: "PVH Corp.", symbol: "PVH"},
        {name: "Qorvo", symbol: "QRVO"},
        {name: "QUALCOMM Inc.", symbol: "QCOM"},
        {name: "Quanta Services Inc.", symbol: "PWR"},
        {name: "Quest Diagnostics", symbol: "DGX"},
        {name: "Range Resources Corp.", symbol: "RRC"},
        {name: "Raytheon Co.", symbol: "RTN"},
        {name: "Realty Income Corporation", symbol: "O"},
        {name: "Red Hat Inc.", symbol: "RHT"},
        {name: "Regeneron", symbol: "REGN"},
        {name: "Regions Financial Corp.", symbol: "RF"},
        {name: "Republic Services Inc", symbol: "RSG"},
        {name: "Reynolds American Inc.", symbol: "RAI"},
        {name: "Robert Half International", symbol: "RHI"},
        {name: "Rockwell Automation Inc.", symbol: "ROK"},
        {name: "Rockwell Collins", symbol: "COL"},
        {name: "Roper Industries", symbol: "ROP"},
        {name: "Ross Stores", symbol: "ROST"},
        {name: "Royal Caribbean Cruises Ltd", symbol: "RCL"},
        {name: "Ryder System", symbol: "R"},
        {name: "S&P Global, Inc.", symbol: "SPGI"},
        {name: "Salesforce.com", symbol: "CRM"},
        {name: "SCANA Corp", symbol: "SCG"},
        {name: "Schlumberger Ltd.", symbol: "SLB"},
        {name: "Scripps Networks Interactive Inc.", symbol: "SNI"},
        {name: "Seagate Technology", symbol: "STX"},
        {name: "Sealed Air Corp.(New)", symbol: "SEE"},
        {name: "Sempra Energy", symbol: "SRE"},
        {name: "Sherwin-Williams", symbol: "SHW"},
        {name: "Signet Jewelers", symbol: "SIG"},
        {name: "Simon Property Group Inc", symbol: "SPG"},
        {name: "Skyworks Solutions", symbol: "SWKS"},
        {name: "SL Green Realty", symbol: "SLG"},
        {name: "Smucker (J.M.)", symbol: "SJM"},
        {name: "Snap-On Inc.", symbol: "SNA"},
        {name: "Southern Co.", symbol: "SO"},
        {name: "Southwest Airlines", symbol: "LUV"},
        {name: "Southwestern Energy", symbol: "SWN"},
        {name: "Spectra Energy Corp.", symbol: "SE"},
        {name: "St Jude Medical", symbol: "STJ"},
        {name: "Stanley Black & Decker", symbol: "SWK"},
        {name: "Staples Inc.", symbol: "SPLS"},
        {name: "Starbucks Corp.", symbol: "SBUX"},
        {name: "Starwood Hotels & Resorts", symbol: "HOT"},
        {name: "State Street Corp.", symbol: "STT"},
        {name: "Stericycle Inc", symbol: "SRCL"},
        {name: "Stryker Corp.", symbol: "SYK"},
        {name: "SunTrust Banks", symbol: "STI"},
        {name: "Symantec Corp.", symbol: "SYMC"},
        {name: "Synchrony Financial", symbol: "SYF"},
        {name: "Sysco Corp.", symbol: "SYY"},
        {name: "T. Rowe Price Group", symbol: "TROW"},
        {name: "Target Corp.", symbol: "TGT"},
        {name: "TE Connectivity Ltd.", symbol: "TEL"},
        {name: "Tegna", symbol: "TGNA"},
        {name: "Teradata Corp.", symbol: "TDC"},
        {name: "Tesoro Petroleum Co.", symbol: "TSO"},
        {name: "Texas Instruments", symbol: "TXN"},
        {name: "Textron Inc.", symbol: "TXT"},
        {name: "The Bank of New York Mellon Corp.", symbol: "BK"},
        {name: "The Clorox Company", symbol: "CLX"},
        {name: "The Coca Cola Company", symbol: "KO"},
        {name: "The Hershey Company", symbol: "HSY"},
        {name: "The Mosaic Company", symbol: "MOS"},
        {name: "The Travelers Companies Inc.", symbol: "TRV"},
        {name: "The Walt Disney Company", symbol: "DIS"},
        {name: "Thermo Fisher Scientific", symbol: "TMO"},
        {name: "Tiffany & Co.", symbol: "TIF"},
        {name: "Time Warner Inc.", symbol: "TWX"},
        {name: "TJX Companies Inc.", symbol: "TJX"},
        {name: "Torchmark Corp.", symbol: "TMK"},
        {name: "Total System Services", symbol: "TSS"},
        {name: "Tractor Supply Company", symbol: "TSCO"},
        {name: "TransDigm Group", symbol: "TDG"},
        {name: "Transocean", symbol: "RIG"},
        {name: "TripAdvisor", symbol: "TRIP"},
        {name: "Twenty-First Century Fox Class A", symbol: "FOXA"},
        {name: "Twenty-First Century Fox Class B", symbol: "FOX"},
        {name: "Tyco International", symbol: "TYC"},
        {name: "Tyson Foods", symbol: "TSN"},
        {name: "U.S. Bancorp", symbol: "USB"},
        {name: "UDR Inc", symbol: "UDR"},
        {name: "Ulta Salon Cosmetics & Fragrance Inc", symbol: "ULTA"},
        {name: "Under Armour", symbol: "UA"},
        {name: "Union Pacific", symbol: "UNP"},
        {name: "United Continental Holdings", symbol: "UAL"},
        {name: "United Health Group Inc.", symbol: "UNH"},
        {name: "United Parcel Service", symbol: "UPS"},
        {name: "United Rentals, Inc.", symbol: "URI"},
        {name: "United Technologies", symbol: "UTX"},
        {name: "Universal Health Services, Inc.", symbol: "UHS"},
        {name: "Unum Group", symbol: "UNM"},
        {name: "Urban Outfitters", symbol: "URBN"},
        {name: "V.F. Corp.", symbol: "VFC"},
        {name: "Valero Energy", symbol: "VLO"},
        {name: "Varian Medical Systems", symbol: "VAR"},
        {name: "Ventas Inc", symbol: "VTR"},
        {name: "Verisign Inc.", symbol: "VRSN"},
        {name: "Verisk Analytics", symbol: "VRSK"},
        {name: "Verizon Communications", symbol: "VZ"},
        {name: "Vertex Pharmaceuticals Inc", symbol: "VRTX"},
        {name: "Viacom Inc.", symbol: "VIAB"},
        {name: "Visa Inc.", symbol: "V"},
        {name: "Vornado Realty Trust", symbol: "VNO"},
        {name: "Vulcan Materials", symbol: "VMC"},
        {name: "Wal-Mart Stores", symbol: "WMT"},
        {name: "Walgreens Boots Alliance", symbol: "WBA"},
        {name: "Waste Management Inc.", symbol: "WM"},
        {name: "Waters Corporation", symbol: "WAT"},
        {name: "Wells Fargo", symbol: "WFC"},
        {name: "Welltower Inc.", symbol: "HCN"},
        {name: "Western Digital", symbol: "WDC"},
        {name: "Western Union Co", symbol: "WU"},
        {name: "Westrock Co", symbol: "WRK"},
        {name: "Weyerhaeuser Corp.", symbol: "WY"},
        {name: "Whirlpool Corp.", symbol: "WHR"},
        {name: "Whole Foods Market", symbol: "WFM"},
        {name: "Williams Cos.", symbol: "WMB"},
        {name: "Willis Towers Watson", symbol: "WLTW"},
        {name: "Wisconsin Energy Corporation", symbol: "WEC"},
        {name: "Wyndham Worldwide", symbol: "WYN"},
        {name: "Wynn Resorts Ltd", symbol: "WYNN"},
        {name: "Xcel Energy Inc", symbol: "XEL"},
        {name: "Xerox Corp.", symbol: "XRX"},
        {name: "Xilinx Inc", symbol: "XLNX"},
        {name: "XL Capital", symbol: "XL"},
        {name: "Xylem Inc.", symbol: "XYL"},
        {name: "Yahoo Inc.", symbol: "YHOO"},
        {name: "Yum! Brands Inc", symbol: "YUM"},
        {name: "Zimmer Biomet Holdings", symbol: "ZBH"},
        {name: "Zions Bancorp", symbol: "ZION"},
        {name: "Zoetis", symbol: "ZTS"}
    ]

}
